<?xml version="1.0" encoding="utf-8"?><Database Name="QLKaraoke" Class="QL_karaokeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Data\QLKaraoke.mdf;Integrated Security=True" SettingsObjectName="quanLyQuanKara.Properties.Settings" SettingsPropertyName="QLKaraokeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.account" Member="accounts">
    <Type Name="account">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="displayName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="userName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.bill" Member="bills">
    <Type Name="bill">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idRoom" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dateCheckIn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="dateCheckOut" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="totalPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="discount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="bill_billInfo" Member="billInfos" ThisKey="id" OtherKey="idBill" Type="billInfo" />
      <Association Name="Room_bill" Member="Room" ThisKey="idRoom" OtherKey="id" Type="Room" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.billInfo" Member="billInfos">
    <Type Name="billInfo">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idBill" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idFood" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="bill_billInfo" Member="bill" ThisKey="idBill" OtherKey="id" Type="bill" IsForeignKey="true" />
      <Association Name="food_billInfo" Member="food" ThisKey="idFood" OtherKey="id" Type="food" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.foodCategory" Member="foodCategories">
    <Type Name="foodCategory">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="isDelete" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="foodCategory_food" Member="foods" ThisKey="id" OtherKey="idCategory" Type="food" />
    </Type>
  </Table>
  <Table Name="dbo.food" Member="foods">
    <Type Name="food">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="idCategory" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="isDelete" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="food_billInfo" Member="billInfos" ThisKey="id" OtherKey="idFood" Type="billInfo" />
      <Association Name="foodCategory_food" Member="foodCategory" ThisKey="idCategory" OtherKey="id" Type="foodCategory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Room" Member="Rooms">
    <Type Name="Room">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="isDelete" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Room_bill" Member="bills" ThisKey="id" OtherKey="idRoom" Type="bill" />
    </Type>
  </Table>
</Database>